[package]
edition = "2021"
name = "pan"
version = "0.1.0"

[[bin]]
name = "pan"
path = "src/main.rs"

[dependencies]
clap = { version = "3.2.20" }
"hermes" = { path = "./hermes" }

[workspace]
members = [
  "hermes",
]
