name: CI
on:
  pull_request:
    paths:
      crates/**
      Cargo.lock
      Cargo.toml
      .gitmodules

concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Set up checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up cache cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Set up build tools
        run: brew install cmake git ninja

      - name: Set up rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          target: wasm32-unknown-unknown

      - name: Test
        run: cargo test
